name: bookit_mobile_app
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+7

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.0.0
  mapbox_maps_flutter: ^2.0.0
  permission_handler: ^11.0.1
  geolocator: ^11.0.0
  flutter_svg: ^1.0.0 
  flutter_localizations:
    sdk: flutter
  

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  connectivity_plus: ^6.1.4
  provider: ^6.1.5
  flutter_riverpod: ^2.6.1
  dio: ^5.8.0+1
  image_picker: ^1.1.2
  package_info_plus: ^8.0.2

  markdown_widget: 2.3.2+8

  intl: ^0.19.0
  

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.4.6
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png" 
  
flutter:
  assets:
    - assets/locale/
    - assets/images/logo.svg
    - assets/images/background.jpeg
    - assets/icons/apple.svg
    - assets/icons/facebook.svg
    - assets/icons/google.svg
    - assets/icons/nav/
    - assets/icons/actions/
    - assets/bookitTermsOfServices/bookit_terms_of_services_en.md
    - assets/bookitTermsOfServices/bookit_terms_of_services_ar.md

  fonts:
    - family: Campton
      fonts:
        - asset: assets/fonts/campton/CamptonBlack.otf
        - asset: assets/fonts/campton/CamptonBlackItalic.otf
        - asset: assets/fonts/campton/CamptonBold.otf
        - asset: assets/fonts/campton/CamptonBoldItalic.otf
        - asset: assets/fonts/campton/CamptonBook.otf
        - asset: assets/fonts/campton/CamptonBookItalic.otf
        - asset: assets/fonts/campton/CamptonExtraBold.otf
        - asset: assets/fonts/campton/CamptonExtraBoldItalic.otf
        - asset: assets/fonts/campton/CamptonExtraLight.otf
        - asset: assets/fonts/campton/CamptonLightItalic.otf
        - asset: assets/fonts/campton/CamptonMedium.otf
        - asset: assets/fonts/campton/CamptonSemiBold.otf
        - asset: assets/fonts/campton/CamptonThin.otf

    - family: SaintRegusSemiBold
      fonts:
        - asset: assets/fonts/saintregus/Sonar Hubermann - SaintRegus-SemiBold.otf
          weight: 600

    - family: SaintRegusSemiBoldCondensed
      fonts:
        - asset: assets/fonts/saintregus/Sonar Hubermann - SaintRegus-SemiBoldCondensed.otf
          weight: 600

    - family: SaintRegusSemiBoldExpanded
      fonts:
        - asset: assets/fonts/saintregus/Sonar Hubermann - SaintRegus-SemiBoldExpanded.otf
          weight: 600

  uses-material-design: true